---
title: "Gov 50 Final Project"
author: Jeremias Castillo
description: "My Final Project"
output:
  distill::distill_article:
    self_contained: false
---

## Project Thoughts

I am interested in exploring the relationship between the total percent of individuals that are considered having a higher risk of falling seriously ill from the COVID-19 virus and the number of high-risk individuals per ICU bed in urban areas across the United States, specifically metropolitan and micropolitan areas and metropolitan divisions. By conducting this analysis, we can see if urban centers with higher percentages of high-risk individuals have fewer ICU beds available, possibly indicating an overall lack of resources that is leaving populations in these areas at a significant disadvantage against the novel virus. This disadvantage would stem from having insufficient resources to safeguard individuals in these communities from being categorized as being high-risk due to underlying health conditions or reasons in the first place. Parallels in this disadvantage could follow if expected trends are followed in number of ICU beds available. 

## Written Proposal  

Do urban areas having a higher total percent of high-risk individuals from COVID-19 translate to larger numbers of high-risk individuals per ICU bed across the United States? I believe that, on average, urban areas in the United States with more at-risk individuals from COVID-19 do translate to more high-risk individuals per ICU bed available in the hospitals there. Historically, urban areas have been densely populated with disadvantaged minority individuals who have been exposed to worsening health disparities. It would not be a surprise if individuals in these urban centers had under-resourced healthcare systems that left them at higher predisposition to being categorized as high-risk in the first place. Parallel to this thought, it would also make sense for there to be more high-risk individuals per ICU bed available in these hospitals. This thinking is established in Nancy Krieger's (1994) theoretical framework of ecosocial theory of disease distribution. The renowned American epidemiologist and Harvard T.H. Chan School of Public Health professor's theory is based on the belief that health outcomes are affected by numerous social determinants of health, including economic resources, and not just the inherent ailment assumption that stereotypically and erroneously follows certain demographics in the health sector. On the basis of my theory, my hypothesis is sound in assuming that there might be some sort of relationship between the total percentage of high-risk individuals and the number of high-risk individuals per ICU bed available. The explanatory variable of interest in this analysis is the total percent of high-risk individuals from COVID-19 per area. This explanatory variable of interest is measured in percentage, repeated for highlighting, and varies by area. The outcome variable of interest is the number of high-risk individuals per ICU bed available by area. This continuous variable is measured in the number of high-risk individuals per ICU bed available in the area. The observed pattern in the data that would support my hypothesis would be if there was a some sort of a significant positive correlation between the total percent of high-risk individuals and the number of high-risk individuals per ICU bed. Patterns suggesting any sort of a significant negative correlation between these two variables would provide evidence against my hypothesis; this would show specific under-funding of hospitals' intensive care units rather than parallel under-funding of the healthcare system, in general. Signs of no significant correlation would also disprove my hypothesis; there would be no relationship between the two variables being observed, directing our attention to other aspects of this subject that could be observed. These relationships could be observed via plotting but also linear regression modeling. Regardless, this study is important to conduct as the analyses done could help public-health officials and healthcare/hospital managers better direct funding amidst pandemics, epidemics, and outbreaks that could impact urban centers similarly to how COVID-19 has.

## Data Visualization

```{r}
library(tidyverse)
covid <- read_csv("data/mmsa-icu-beds.csv")
covid$total_percent_at_risk <- gsub("%", "", paste(covid$total_percent_at_risk))

covid |>
  ggplot(mapping = aes(x = as.numeric(total_percent_at_risk), y = high_risk_per_ICU_bed)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Total % of High-Risk Individuals vs. # of High-Risk Individuals Per ICU Bed",
    x = "Total Percent of Individuals at High Risk",
    y = "Number of High-Risk Individuals Per ICU Bed",
    subtitle = "Among Major US Urban Center",
    caption = "Source: CDC's BRFSS (2017) & KFF (2018-2019)"
  )
```
